### ISSUE TITLE
Display possible options instead of just errors when missing required flags

### ISSUE THREAD

**Issue by karlprieb** [ardriveapp/ardrive-cli#189]
When running a command with missing required flags we should return the error and some guidance.

Example with `tx-status`:
```
ardrive tx-status
error: required option '-t --tx-id <txId>' not specified
```

Instead of just showing the error we could ask for a txId input like:
```
ardrive tx-status
error: required option '-t --tx-id <txId>' not specified
Transaction ID to check: <user input>
```

A `--no-option` global flag is also needed to skip this behavior if wanted.

**Comment by agsuy** [comment]
Tracking this one internally.
