### ISSUE TITLE
Make it clear that the user can cancel the program

### ISSUE THREAD

**Issue by karlprieb** [ardriveapp/ardrive-cli#191]
From: https://clig.dev/#interactivity

**Let the user escape.** Make it clear how to get out. (Don’t do what vim does.) If your program hangs on network I/O etc, always make Ctrl-C still work. If it’s a wrapper around program execution where Ctrl-C can’t quit (SSH, tmux, telnet, etc), make it clear how to do that. For example, SSH allows escape sequences with the ~ escape character.

Currently, all commands will exit when Ctrl-C, but we can have a fixed message saying that you can Ctrl-C to quit.

**Comment by agsuy** [comment]
Tracking this one internally.
