### ISSUE TITLE
Human readable output

### ISSUE THREAD

**Issue by karlprieb** [ardriveapp/ardrive-cli#197]
It's hard to read JSON output, it would be so much better if we display a table and have a `--json` flag to display JSON.
I love JSON output, make it easy to pipe to `jq`, but I believe most users just want to get an easy to read output and have the option to output JSON when they require it.

Example of `ardrive file-info -f 9e5a1dcd-f972-4c45-bb49-61659e95a197` human readable output:
```
Name                Date      Last Modified  Size   Content Type
------------------  --------  -------------  -----  --------------------
Quincas Borba.epub  01/01/01  01/01/01       280kb  application/epub+zip
```
Shows what really matters of file information by default, and add flags to show more information.

**Comment by agsuy** [comment]
Tracking this one internally.
