### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by karlprieb** [ardriveapp/ardrive-cli#203]
It would be good if we can package the program so the user doesn't need to have NodeJS installed.
We could have more control delivering the package with the NodeJS version that we support, and it's easier to just install a package.

References:
* https://github.com/vercel/pkg
* https://deno.land/manual/tools/compiler
* https://github.com/leafac/caxa/
* https://github.com/nexe/nexe

**Comment by agsuy** [comment]
Tracking this one internally.
