### ISSUE TITLE
Wallet Balance Error

### ISSUE THREAD

**Issue by saraspaudel** [ardriveapp/ardrive-cli#222]
I am getting the following error which makes no sense, 1837230936333 > 1802248806364

`Error: Wallet balance of 1837230936333 Winston is not enough (1802248806364) for data upload of size 6783337646 bytes!`

**Comment by agsuy** [comment]
Can u provide the command you were using?

**Comment by agsuy** [comment]
This was part of an old an deprecated estimation. Closing
