### ISSUE TITLE
CLI can't list drive after uploading

### ISSUE THREAD

**Issue by pescennius** [ardriveapp/ardrive-cli#352]
I uploaded a few directories to a public drive using the ardrive cli. The puli The uploads seem to have been successful. However, if I try to list the drive using the cli, I get errors:

```
Provided custom metadata GQL tag name collides with a protected ArFS protected tag: Cipher
```

 This works before the upload so it appears the cli is uploading files that are malformed

to reproduce
```sh
ardrive list-folder --parent-folder-id "7764773b-8935-48c7-a97e-b1a8b54a6335"
```

**Comment by thiagocarvalhodev** [comment]
Hi @pescennius,

I checked your folder, and it appears that the drive is private. 
The Drive-ID of the folder is `573dfb73-9e43-45ac-8e95-593858a78438`.

You'll be able to list your files by using the following command:
``` bash
ardrive list-folder --parent-folder-id "7764773b-8935-48c7-a97e-b1a8b54a6335" -w /my/wallet.json -P
```

This should resolve the issue you’re encountering.

Let me know if you need something else from us!

**Comment by pescennius** [comment]
@thiagocarvalhodev I don't believe thisis correct. The drive ID is but if you use the cli to look at it you will see that it is public.

```sh
ardrive drive-info -d "573dfb73-9e43-45ac-8e95-593858a78438"
```

```json
{
    "appName": "ArDrive-App",
    "appVersion": "2.48.2",
    "arFS": "0.14",
    "contentType": "application/json",
    "driveId": "573dfb73-9e43-45ac-8e95-593858a78438",
    "entityType": "drive",
    "name": "Empty",
    "txId": "ecKuT_tUwvOsYl06rTV8ZBgCxwhIBOMr3SfO0p_7Pt0",
    "unixTime": 1720295404,
    "customMetaDataGqlTags": {
        "App-Platform": "Web"
    },
    "drivePrivacy": "public",
    "rootFolderId": "7764773b-8935-48c7-a97e-b1a8b54a6335"
}
```

**Comment by thiagocarvalhodev** [comment]
I understand the issue now. I'm sorry for the mistake. I looked at the folders/files in this drive, and they include the tags Cipher and Cipher-IV, which are typically used for private entities.

It seems the CLI might be mistakenly applying these tags, causing the conflict. We’re looking into this and will update you shortly.

**Comment by pescennius** [comment]
Thanks @thiagocarvalhodev I appreciate the help. Makes sense about the tags. Would this explain why the UI doesn't render those files either?

**Comment by thiagocarvalhodev** [comment]
@pescennius , probably yes! If the tags are present it means the file is encrypted. I checked and those files are indeed encrypted. As the app thinks those files are public, we try to parse the metadata JSON without decryption, and it fails.

**Comment by pescennius** [comment]
I see, so since there is dirty state, there has to be some handling for that somehow no?

**Comment by thiagocarvalhodev** [comment]
Hi @pescennius,

We’ve identified the issue where the CLI can’t list the drive after uploading due to an incorrect privacy state of the drive.

The issue with uploading with the wrong privacy state was already fixed in version `2.0.5`.

We have implemented a solution in version `2.0.6` that will skip the broken entities when listing the drive or folder. Please update to the latest version and try again.

If you encounter any further issues, feel free to let us know.

**Comment by pescennius** [comment]
@thiagocarvalhodev I upgraded to 2.0.6 and I still got the same issue running `ardrive list-folder --parent-folder-id "7764773b-8935-48c7-a97e-b1a8b54a6335"`

**Comment by pescennius** [comment]
@thiagocarvalhodev any updates?

**Comment by thiagocarvalhodev** [comment]
Hi @pescennius,

Sorry for the delay!!!

I ran the same command, and it returned an empty list. That’s expected in your case. The reason is that the corrupted entities can’t be listed, so they’re skipped when fetching the folder.

```bash
ardrive -V
2.0.6

ardrive list-folder --parent-folder-id "7764773b-8935-48c7-a97e-b1a8b54a6335"
Provided custom metadata GQL tag name collides with a protected ArFS protected tag: Cipher
Parsed an invalid custom metadata shape from MetaData Tx GQL Tags: [object Object]
Provided custom metadata GQL tag name collides with a protected ArFS protected tag: Cipher
Parsed an invalid custom metadata shape from MetaData Tx GQL Tags: [object Object]
Provided custom metadata GQL tag name collides with a protected ArFS protected tag: Cipher
Parsed an invalid custom metadata shape from MetaData Tx GQL Tags: [object Object]
Provided custom metadata GQL tag name collides with a protected ArFS protected tag: Cipher
Parsed an invalid custom metadata shape from MetaData Tx GQL Tags: [object Object]
Provided custom metadata GQL tag name collides with a protected ArFS protected tag: Cipher
Parsed an invalid custom metadata shape from MetaData Tx GQL Tags: [object Object]
Provided custom metadata GQL tag name collides with a protected ArFS protected tag: Cipher
Parsed an invalid custom metadata shape from MetaData Tx GQL Tags: [object Object]
Provided custom metadata GQL tag name collides with a protected ArFS protected tag: Cipher
Parsed an invalid custom metadata shape from MetaData Tx GQL Tags: [object Object]
Error building folder. Skipping... Error: SyntaxError: Unexpected token  in JSON at position 0
Error building folder. Skipping... Error: SyntaxError: Unexpected token ; in JSON at position 0
Error building folder. Skipping... Error: SyntaxError: Unexpected token ! in JSON at position 0
Error building folder. Skipping... Error: SyntaxError: Unexpected token  in JSON at position 0
Error building folder. Skipping... Error: SyntaxError: Unexpected token � in JSON at position 0
Error building folder. Skipping... Error: SyntaxError: Unexpected token x in JSON at position 0
Error building folder. Skipping... Error: SyntaxError: Unexpected token ԰ in JSON at position 0
[]
```

**Comment by pescennius** [comment]
@thiagocarvalhodev understood. I saw all the warning logs and thought it was an error again but the exit code confirms that you are right. Is there a way to disable those error logs?

**Comment by thiagocarvalhodev** [comment]
Hi @pescennius,

Thank you for your patience and for reporting the bug!
Closing this issue now. Thank you again for your effort in helping us improve! ♥️
