### ISSUE TITLE
Unhandled exception at ArDrive Login Password prompt

### ISSUE THREAD

**Issue by Silanael** [ardriveapp/ardrive-cli#39]
Unhandled exception ENETUNREACH, firing if network connection is not present when entering the login prompt.

![Screenshot from 2021-09-19 22-27-05](https://user-images.githubusercontent.com/81468510/133940478-df59f44e-1aa9-4cf7-92d8-38d4dce39eef.png)

**Comment by vilenarios** [comment]
This is an issue relating to the legacy CLI, now labeled "ArDrive-Sync" and moved here https://github.com/ardriveapp/ardrive-sync It is an alpha product, and not in support at this time.
