### ISSUE TITLE
Documentation for using the cli

### ISSUE THREAD

**Issue by elpiel** [ardriveapp/ardrive-cli#42]
I can't seem to find any documentation regarding how to use the cli.

Maybe I can't find the link because it's too hidden?

I will try it tomorrow anyway but would be nice to have usage examples or some kind of documentation 😋

**Comment by Silanael** [comment]
Feel free to check out documentation I wrote for my docker-image of the CLI: https://github.com/Silanael/ardrive-cli-v1/blob/master/README.md

It should give you a basic understanding on how the CLI works. Just ignore the docker/container -related parts.

**Comment by agsuy** [comment]
@elpiel  we updated the CLI with a brand new and comprehensive readme.

Closing this one.
