### ISSUE TITLE
Drives not fetched properly after initialization

### ISSUE THREAD

**Issue by Silanael** [ardriveapp/ardrive-cli#43]
During subsequent runs after init, the CLI fails to fetch drives from Arweave, presenting only the new drive creation prompt.

This happens when the drive is created with something else than the CLI (ardrive-web / app.ardrive.io) and seems to be an issue with both public and private drives. In my testing, the drive was mined and verified, and adding files to it through the web didn't make a difference.

Metadata-transactions for the drive and the root folder:
![Screenshot from 2021-09-24 13-33-04](https://user-images.githubusercontent.com/81468510/134666305-bad6161a-2e30-457e-a7c5-ead5645927b1.png)

How the CLI behaves when trying to add the drive:
![Screenshot from 2021-09-24 13-33-42](https://user-images.githubusercontent.com/81468510/134666379-afafb9bf-9bbf-4fa4-9b60-d6cf09e0f8f1.png)

(The drive added is private. Same behaviour observed for public drives.)

**Comment by agsuy** [comment]
This does not apply to new 1.0.0 version.

Closing.
