### ISSUE TITLE
check all strings for grammar/typos

### ISSUE THREAD

**Issue by trippedout** [ardriveapp/ardrive-cli#5]
try and keep all string usage in a central module (esp if planning on dealing with il8n later) and make sure we dont have typos like: `No existing Private ArDrives found.  Creating a new, default new one.`

**Comment by trippedout** [comment]
also make sure that pathing is displayed correctly - notice the double slash in this output:
```
Folder not found.  Creating new directory at /Users/atripaldi/Dev/Personal/ArDrive/ardrive-cli/Backup/
Writing your ArDrive Wallet backup to /Users/atripaldi/Dev/Personal/ArDrive/ardrive-cli/Backup//ArDrive_Backup_trip.json
```

**Comment by ardriveapp** [comment]
Typos are corrected and text has been revamped.  

That string in particular on path was changed to a / instead of sep.  Not sure if this will be effective though, as it shows up okay on Windows.
